global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'shardflow-java'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['java:8200']
        labels:
          service: 'shardflow-system'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
