spring:
  application:
    name: shardflow-system
  datasource:
    url: jdbc:postgresql://localhost:5432/shardflow
    username: shardflow
    password: shardflow
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8200

logging:
  level:
    com.shardflow: INFO
