-- ============================================================
-- ShardFlow Schema (PostgreSQL 18)
-- 唯一建表脚本 — shardflow-app 模块
-- ============================================================

CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP(3);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
;

-- 1. 用户与认证
CREATE TABLE shardflow_user (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT         NOT NULL,
    password_hash   TEXT         NOT NULL,
    user_id         TEXT         NOT NULL,
    role            TEXT         NOT NULL DEFAULT 'USER',
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_username UNIQUE (username),
    CONSTRAINT uk_user_id   UNIQUE (user_id)
)
;
COMMENT ON TABLE shardflow_user IS '用户账户表';
COMMENT ON COLUMN shardflow_user.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_user.username IS '登录用户名，唯一';
COMMENT ON COLUMN shardflow_user.password_hash IS '密码哈希值';
COMMENT ON COLUMN shardflow_user.user_id IS '用户业务标识，唯一，用于跨模块关联';
COMMENT ON COLUMN shardflow_user.role IS '角色：USER | ADMIN';
COMMENT ON COLUMN shardflow_user.enabled IS '账户是否启用';
COMMENT ON COLUMN shardflow_user.created_at IS '创建时间';

-- 2. 任务与会话
CREATE TABLE shardflow_task (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_code       TEXT         NOT NULL,
    user_id         TEXT         NOT NULL,
    title           TEXT,
    description     TEXT,
    status          TEXT         NOT NULL DEFAULT 'PENDING',
    session_id      TEXT,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_task_code UNIQUE (task_code)
)
;
CREATE INDEX idx_task_user   ON shardflow_task (user_id)
;
CREATE INDEX idx_task_status ON shardflow_task (status)
;
CREATE TRIGGER trg_shardflow_task_updated_at
    BEFORE UPDATE ON shardflow_task
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON TABLE shardflow_task IS '任务主表，记录用户创建的对话任务';
COMMENT ON COLUMN shardflow_task.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_task.task_code IS '任务编码，唯一标识';
COMMENT ON COLUMN shardflow_task.user_id IS '所属用户标识';
COMMENT ON COLUMN shardflow_task.title IS '任务标题';
COMMENT ON COLUMN shardflow_task.description IS '任务描述';
COMMENT ON COLUMN shardflow_task.status IS '任务状态：PENDING | RUNNING | COMPLETED | CANCELLED';
COMMENT ON COLUMN shardflow_task.session_id IS '当前活跃会话ID';
COMMENT ON COLUMN shardflow_task.created_at IS '创建时间';
COMMENT ON COLUMN shardflow_task.updated_at IS '最后更新时间（触发器自动维护）';

CREATE TABLE shardflow_task_session (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     TEXT         NOT NULL,
    user_id     TEXT         NOT NULL,
    session_seq INTEGER      NOT NULL DEFAULT 0,
    source_port TEXT,
    status      TEXT         NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)
;
CREATE INDEX idx_ts_task ON shardflow_task_session (task_id)
;
CREATE INDEX idx_ts_user ON shardflow_task_session (user_id)
;
COMMENT ON TABLE shardflow_task_session IS '任务会话表，记录同一任务下的多次会话（跨端口续接）';
COMMENT ON COLUMN shardflow_task_session.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_task_session.task_id IS '关联任务编码';
COMMENT ON COLUMN shardflow_task_session.user_id IS '所属用户标识';
COMMENT ON COLUMN shardflow_task_session.session_seq IS '会话序号，从0递增';
COMMENT ON COLUMN shardflow_task_session.source_port IS '来源端口：web | desktop | mobile | api';
COMMENT ON COLUMN shardflow_task_session.status IS '会话状态：ACTIVE | ENDED';
COMMENT ON COLUMN shardflow_task_session.created_at IS '创建时间';

-- 3. Agent 配置
CREATE TABLE shardflow_agent_config (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_code    TEXT         NOT NULL,
    user_id       TEXT         NOT NULL,
    model_id      TEXT,
    name          TEXT         NOT NULL,
    description   TEXT,
    system_prompt TEXT,
    temperature   DOUBLE PRECISION DEFAULT 0.7,
    max_tokens    INTEGER      DEFAULT 4096,
    tools         JSONB,
    created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_code UNIQUE (agent_code)
)
;
CREATE INDEX idx_agent_config_user    ON shardflow_agent_config (user_id)
;
CREATE INDEX idx_agent_config_tools_gin ON shardflow_agent_config USING GIN (tools)
;
CREATE TRIGGER trg_shardflow_agent_config_updated_at
    BEFORE UPDATE ON shardflow_agent_config
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON TABLE shardflow_agent_config IS 'Agent配置表，存储用户自定义的助手实例';
COMMENT ON COLUMN shardflow_agent_config.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_agent_config.agent_code IS 'Agent编码，唯一标识';
COMMENT ON COLUMN shardflow_agent_config.user_id IS '所属用户标识';
COMMENT ON COLUMN shardflow_agent_config.model_id IS '关联模型编码';
COMMENT ON COLUMN shardflow_agent_config.name IS 'Agent显示名称';
COMMENT ON COLUMN shardflow_agent_config.description IS 'Agent描述';
COMMENT ON COLUMN shardflow_agent_config.system_prompt IS '系统提示词';
COMMENT ON COLUMN shardflow_agent_config.temperature IS '采样温度，默认0.7';
COMMENT ON COLUMN shardflow_agent_config.max_tokens IS '最大输出token数，默认4096';
COMMENT ON COLUMN shardflow_agent_config.tools IS '可用工具列表，JSONB格式';
COMMENT ON COLUMN shardflow_agent_config.created_at IS '创建时间';
COMMENT ON COLUMN shardflow_agent_config.updated_at IS '最后更新时间（触发器自动维护）';

-- 4. 模型管理
CREATE TABLE shardflow_model_builtin (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code      TEXT         NOT NULL,
    name            TEXT         NOT NULL,
    provider        TEXT         NOT NULL,
    model           TEXT         NOT NULL,
    base_url        TEXT,
    api_key_env     TEXT,
    capabilities    JSONB,
    context_window  INTEGER      DEFAULT 4096,
    is_enabled      BOOLEAN      DEFAULT TRUE,
    sort_order      INTEGER      DEFAULT 0,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_builtin_model_code UNIQUE (model_code)
)
;
CREATE INDEX idx_model_builtin_cap_gin ON shardflow_model_builtin USING GIN (capabilities)
;
CREATE TRIGGER trg_shardflow_model_builtin_updated_at
    BEFORE UPDATE ON shardflow_model_builtin
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON TABLE shardflow_model_builtin IS '内置模型表，系统预置的LLM模型配置';
COMMENT ON COLUMN shardflow_model_builtin.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_model_builtin.model_code IS '模型编码，唯一标识';
COMMENT ON COLUMN shardflow_model_builtin.name IS '模型显示名称';
COMMENT ON COLUMN shardflow_model_builtin.provider IS '模型供应商：openai | deepseek | anthropic';
COMMENT ON COLUMN shardflow_model_builtin.model IS '模型API标识名';
COMMENT ON COLUMN shardflow_model_builtin.base_url IS 'API基础URL';
COMMENT ON COLUMN shardflow_model_builtin.api_key_env IS 'API密钥环境变量名';
COMMENT ON COLUMN shardflow_model_builtin.capabilities IS '能力标签数组，如["chat","vision","reasoning"]';
COMMENT ON COLUMN shardflow_model_builtin.context_window IS '上下文窗口大小（token数）';
COMMENT ON COLUMN shardflow_model_builtin.is_enabled IS '是否启用';
COMMENT ON COLUMN shardflow_model_builtin.sort_order IS '排序权重，越小越靠前';
COMMENT ON COLUMN shardflow_model_builtin.created_at IS '创建时间';
COMMENT ON COLUMN shardflow_model_builtin.updated_at IS '最后更新时间（触发器自动维护）';

CREATE TABLE shardflow_custom_model (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code        TEXT         NOT NULL,
    user_id           TEXT         NOT NULL,
    name              TEXT         NOT NULL,
    provider          TEXT         NOT NULL,
    base_url          TEXT,
    model             TEXT         NOT NULL,
    api_key_id        TEXT,
    api_key_encrypted TEXT,
    capabilities      JSONB,
    context_window    INTEGER      DEFAULT 4096,
    enabled           BOOLEAN      DEFAULT TRUE,
    is_verified       BOOLEAN      DEFAULT FALSE,
    created_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_model_code UNIQUE (model_code)
)
;
CREATE INDEX idx_custom_model_user     ON shardflow_custom_model (user_id)
;
CREATE INDEX idx_custom_model_cap_gin  ON shardflow_custom_model USING GIN (capabilities)
;
COMMENT ON TABLE shardflow_custom_model IS '自定义模型表，用户自行接入的LLM模型';
COMMENT ON COLUMN shardflow_custom_model.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_custom_model.model_code IS '模型编码，唯一标识';
COMMENT ON COLUMN shardflow_custom_model.user_id IS '所属用户标识';
COMMENT ON COLUMN shardflow_custom_model.name IS '模型显示名称';
COMMENT ON COLUMN shardflow_custom_model.provider IS '模型供应商';
COMMENT ON COLUMN shardflow_custom_model.base_url IS 'API基础URL';
COMMENT ON COLUMN shardflow_custom_model.model IS '模型API标识名';
COMMENT ON COLUMN shardflow_custom_model.api_key_id IS 'API密钥存储ID';
COMMENT ON COLUMN shardflow_custom_model.api_key_encrypted IS '加密后的API密钥';
COMMENT ON COLUMN shardflow_custom_model.capabilities IS '能力标签数组';
COMMENT ON COLUMN shardflow_custom_model.context_window IS '上下文窗口大小（token数）';
COMMENT ON COLUMN shardflow_custom_model.enabled IS '是否启用';
COMMENT ON COLUMN shardflow_custom_model.is_verified IS '是否通过平台验证';
COMMENT ON COLUMN shardflow_custom_model.created_at IS '创建时间';

CREATE TABLE shardflow_model_audit_log (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         TEXT         NOT NULL,
    action          TEXT         NOT NULL,
    model_id        TEXT         NOT NULL,
    model_type      TEXT         NOT NULL,
    summary         TEXT,
    success         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)
;
CREATE INDEX idx_model_audit_user           ON shardflow_model_audit_log (user_id)
;
CREATE INDEX idx_model_audit_model          ON shardflow_model_audit_log (model_id)
;
CREATE INDEX idx_model_audit_created        ON shardflow_model_audit_log (created_at DESC)
;
CREATE INDEX idx_model_audit_created_brin   ON shardflow_model_audit_log USING BRIN (created_at)
;
COMMENT ON TABLE shardflow_model_audit_log IS '模型操作审计日志，记录模型的增删改操作';
COMMENT ON COLUMN shardflow_model_audit_log.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_model_audit_log.user_id IS '操作用户标识';
COMMENT ON COLUMN shardflow_model_audit_log.action IS '操作类型：CREATE | UPDATE | DELETE';
COMMENT ON COLUMN shardflow_model_audit_log.model_id IS '被操作的模型编码';
COMMENT ON COLUMN shardflow_model_audit_log.model_type IS '模型类型：builtin | custom';
COMMENT ON COLUMN shardflow_model_audit_log.summary IS '操作摘要';
COMMENT ON COLUMN shardflow_model_audit_log.success IS '操作是否成功';
COMMENT ON COLUMN shardflow_model_audit_log.created_at IS '操作时间';

-- 5. 知识库
CREATE TABLE shardflow_kb_collection (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_code TEXT         NOT NULL,
    user_id         TEXT         NOT NULL,
    name            TEXT         NOT NULL,
    description     TEXT,
    icon            TEXT,
    status          TEXT         NOT NULL DEFAULT 'ACTIVE',
    doc_count       INTEGER      DEFAULT 0,
    chunk_count     INTEGER      DEFAULT 0,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_collection_code UNIQUE (collection_code)
)
;
CREATE INDEX idx_kb_coll_user ON shardflow_kb_collection (user_id)
;
CREATE TRIGGER trg_shardflow_kb_collection_updated_at
    BEFORE UPDATE ON shardflow_kb_collection
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON TABLE shardflow_kb_collection IS '知识库集合表，管理用户创建的知识库';
COMMENT ON COLUMN shardflow_kb_collection.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_kb_collection.collection_code IS '集合编码，唯一标识';
COMMENT ON COLUMN shardflow_kb_collection.user_id IS '所属用户标识';
COMMENT ON COLUMN shardflow_kb_collection.name IS '知识库名称';
COMMENT ON COLUMN shardflow_kb_collection.description IS '知识库描述';
COMMENT ON COLUMN shardflow_kb_collection.icon IS '知识库图标标识';
COMMENT ON COLUMN shardflow_kb_collection.status IS '状态：ACTIVE | ARCHIVED | DELETED';
COMMENT ON COLUMN shardflow_kb_collection.doc_count IS '文档数量';
COMMENT ON COLUMN shardflow_kb_collection.chunk_count IS '分块数量';
COMMENT ON COLUMN shardflow_kb_collection.created_at IS '创建时间';
COMMENT ON COLUMN shardflow_kb_collection.updated_at IS '最后更新时间（触发器自动维护）';

CREATE TABLE shardflow_kb_document (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code   TEXT         NOT NULL,
    collection_id   TEXT         NOT NULL,
    user_id         TEXT         NOT NULL,
    filename        TEXT         NOT NULL,
    file_type       TEXT,
    file_size       BIGINT       DEFAULT 0,
    minio_url       TEXT,
    parse_strategy  TEXT,
    status          TEXT         NOT NULL DEFAULT 'PENDING',
    error_msg       TEXT,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_document_code UNIQUE (document_code)
)
;
CREATE INDEX idx_kb_doc_collection ON shardflow_kb_document (collection_id)
;
CREATE INDEX idx_kb_doc_user       ON shardflow_kb_document (user_id)
;
COMMENT ON TABLE shardflow_kb_document IS '知识库文档表，记录上传的原始文档信息';
COMMENT ON COLUMN shardflow_kb_document.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_kb_document.document_code IS '文档编码，唯一标识';
COMMENT ON COLUMN shardflow_kb_document.collection_id IS '所属集合编码';
COMMENT ON COLUMN shardflow_kb_document.user_id IS '所属用户标识';
COMMENT ON COLUMN shardflow_kb_document.filename IS '原始文件名';
COMMENT ON COLUMN shardflow_kb_document.file_type IS '文件类型：pdf | docx | txt | md';
COMMENT ON COLUMN shardflow_kb_document.file_size IS '文件大小（字节）';
COMMENT ON COLUMN shardflow_kb_document.minio_url IS 'MinIO对象存储路径';
COMMENT ON COLUMN shardflow_kb_document.parse_strategy IS '解析策略：auto | manual';
COMMENT ON COLUMN shardflow_kb_document.status IS '处理状态：PENDING | PROCESSING | COMPLETED | FAILED';
COMMENT ON COLUMN shardflow_kb_document.error_msg IS '处理失败时的错误信息';
COMMENT ON COLUMN shardflow_kb_document.created_at IS '创建时间';

CREATE TABLE shardflow_kb_strategy (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_id     TEXT         NOT NULL,
    user_id         TEXT         NOT NULL,
    task_type       TEXT         NOT NULL,
    query_pattern   TEXT         NOT NULL,
    source_combo    TEXT         NOT NULL,
    success_score   DOUBLE PRECISION DEFAULT 0,
    cost_ms         INTEGER      DEFAULT 0,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_strategy_id UNIQUE (strategy_id)
)
;
CREATE INDEX idx_strategy_user      ON shardflow_kb_strategy (user_id)
;
CREATE INDEX idx_strategy_task_type ON shardflow_kb_strategy (task_type)
;
COMMENT ON TABLE shardflow_kb_strategy IS '知识库策略表，记录检索策略的效果评估';
COMMENT ON COLUMN shardflow_kb_strategy.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_kb_strategy.strategy_id IS '策略编码，唯一标识';
COMMENT ON COLUMN shardflow_kb_strategy.user_id IS '所属用户标识';
COMMENT ON COLUMN shardflow_kb_strategy.task_type IS '任务类型';
COMMENT ON COLUMN shardflow_kb_strategy.query_pattern IS '查询模式';
COMMENT ON COLUMN shardflow_kb_strategy.source_combo IS '数据源组合';
COMMENT ON COLUMN shardflow_kb_strategy.success_score IS '成功率评分';
COMMENT ON COLUMN shardflow_kb_strategy.cost_ms IS '耗时（毫秒）';
COMMENT ON COLUMN shardflow_kb_strategy.created_at IS '创建时间';

-- 6. 记忆架构
CREATE TABLE memory_chunks (
    chunk_id            TEXT         PRIMARY KEY,
    user_id             TEXT         NOT NULL,
    memory_type         TEXT         NOT NULL,
    category            TEXT         NOT NULL,
    content_text        TEXT,
    content_structured  JSONB,
    confidence          NUMERIC(3,2) DEFAULT 1.00,
    source              TEXT         NOT NULL,
    source_session_id   TEXT,
    metadata            JSONB,
    has_conflict        BOOLEAN      DEFAULT FALSE,
    conflict_with       TEXT,
    resolution_status   TEXT,
    is_deleted          BOOLEAN      DEFAULT FALSE,
    created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    expires_at          TIMESTAMPTZ(3)
)
;
CREATE INDEX idx_mc_user_type     ON memory_chunks (user_id, memory_type)
;
CREATE INDEX idx_mc_category      ON memory_chunks (category)
;
CREATE INDEX idx_mc_created_at    ON memory_chunks (created_at)
;
CREATE INDEX idx_mc_confidence    ON memory_chunks (confidence)
;
CREATE INDEX idx_mc_expires_at    ON memory_chunks (expires_at)
;
CREATE INDEX idx_mc_content_gin   ON memory_chunks USING GIN (content_structured)
;
CREATE INDEX idx_mc_meta_gin      ON memory_chunks USING GIN (metadata)
;
CREATE TRIGGER trg_memory_chunks_updated_at
    BEFORE UPDATE ON memory_chunks
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON TABLE memory_chunks IS '记忆片段明细表';
COMMENT ON COLUMN memory_chunks.chunk_id IS '片段唯一标识';
COMMENT ON COLUMN memory_chunks.user_id IS '所属用户标识';
COMMENT ON COLUMN memory_chunks.memory_type IS '记忆类型：short_term | semantic | episodic';
COMMENT ON COLUMN memory_chunks.category IS '记忆分类标签';
COMMENT ON COLUMN memory_chunks.content_text IS '文本内容';
COMMENT ON COLUMN memory_chunks.content_structured IS '结构化内容，JSONB格式';
COMMENT ON COLUMN memory_chunks.confidence IS '置信度，0.00~1.00';
COMMENT ON COLUMN memory_chunks.source IS 'conversation|explicit_confirmation|ner_extraction|scheduled_task';
COMMENT ON COLUMN memory_chunks.source_session_id IS '来源会话ID';
COMMENT ON COLUMN memory_chunks.metadata IS '元数据，JSONB格式';
COMMENT ON COLUMN memory_chunks.has_conflict IS '是否存在冲突';
COMMENT ON COLUMN memory_chunks.conflict_with IS '冲突的片段ID';
COMMENT ON COLUMN memory_chunks.resolution_status IS '冲突解决状态：pending | resolved | ignored';
COMMENT ON COLUMN memory_chunks.is_deleted IS '软删除标记';
COMMENT ON COLUMN memory_chunks.created_at IS '创建时间';
COMMENT ON COLUMN memory_chunks.updated_at IS '最后更新时间（触发器自动维护）';
COMMENT ON COLUMN memory_chunks.expires_at IS '过期时间，用于短期记忆自动清理';

CREATE TABLE session_state_summaries (
    summary_id         TEXT         PRIMARY KEY,
    user_id            TEXT         NOT NULL,
    task_id            TEXT         NOT NULL,
    session_seq        INTEGER      NOT NULL DEFAULT 1,
    task_type          TEXT,
    task_goal          TEXT,
    compressed_history TEXT,
    knowledge_state    JSONB        NOT NULL,
    user_context       JSONB,
    execution_state    JSONB,
    source_preference  JSONB,
    version            INTEGER      DEFAULT 1,
    is_deleted         BOOLEAN      DEFAULT FALSE,
    created_at         TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at         TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)
;
CREATE INDEX idx_sss_user_task  ON session_state_summaries (user_id, task_id)
;
CREATE INDEX idx_sss_task_type  ON session_state_summaries (task_type)
;
CREATE INDEX idx_sss_created_at ON session_state_summaries (created_at)
;
CREATE INDEX idx_sss_ks_gin     ON session_state_summaries USING GIN (knowledge_state)
;
CREATE INDEX idx_sss_uc_gin     ON session_state_summaries USING GIN (user_context)
;
CREATE INDEX idx_sss_es_gin     ON session_state_summaries USING GIN (execution_state)
;
CREATE INDEX idx_sss_sp_gin     ON session_state_summaries USING GIN (source_preference)
;
CREATE TRIGGER trg_session_state_summaries_updated_at
    BEFORE UPDATE ON session_state_summaries
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON TABLE session_state_summaries IS '会话状态快照表（子层B终态）';
COMMENT ON COLUMN session_state_summaries.summary_id IS '快照唯一标识';
COMMENT ON COLUMN session_state_summaries.user_id IS '所属用户标识';
COMMENT ON COLUMN session_state_summaries.task_id IS '关联任务编码';
COMMENT ON COLUMN session_state_summaries.session_seq IS '会话序号';
COMMENT ON COLUMN session_state_summaries.task_type IS '任务类型';
COMMENT ON COLUMN session_state_summaries.task_goal IS '任务目标';
COMMENT ON COLUMN session_state_summaries.compressed_history IS '概念摘要的自然语言版本，直接复用子层A的context_summary';
COMMENT ON COLUMN session_state_summaries.knowledge_state IS 'confirmed/excluded/pending/key_decisions，复用子层A的structured_summary并补充key_decisions';
COMMENT ON COLUMN session_state_summaries.user_context IS '用户上下文快照';
COMMENT ON COLUMN session_state_summaries.execution_state IS '执行状态快照';
COMMENT ON COLUMN session_state_summaries.source_preference IS '数据源偏好';
COMMENT ON COLUMN session_state_summaries.version IS '快照版本号';
COMMENT ON COLUMN session_state_summaries.is_deleted IS '软删除标记';
COMMENT ON COLUMN session_state_summaries.created_at IS '创建时间';
COMMENT ON COLUMN session_state_summaries.updated_at IS '最后更新时间（触发器自动维护）';

CREATE TABLE strategy_records (
    record_id          TEXT         PRIMARY KEY,
    user_id            TEXT         NOT NULL,
    task_type          TEXT         NOT NULL,
    query_pattern      TEXT         NOT NULL,
    tool_combo         JSONB        NOT NULL,
    user_feedback      JSONB,
    success_score      NUMERIC(3,2),
    cost_ms            INTEGER,
    is_deleted         BOOLEAN      DEFAULT FALSE,
    created_at         TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)
;
CREATE INDEX idx_sr_user_type  ON strategy_records (user_id, task_type)
;
CREATE INDEX idx_sr_success    ON strategy_records (success_score)
;
CREATE INDEX idx_sr_created_at ON strategy_records (created_at)
;
CREATE INDEX idx_sr_tc_gin     ON strategy_records USING GIN (tool_combo)
;
CREATE INDEX idx_sr_uf_gin     ON strategy_records USING GIN (user_feedback)
;
COMMENT ON TABLE strategy_records IS '策略记录表';
COMMENT ON COLUMN strategy_records.record_id IS '记录唯一标识';
COMMENT ON COLUMN strategy_records.user_id IS '所属用户标识';
COMMENT ON COLUMN strategy_records.task_type IS '任务类型';
COMMENT ON COLUMN strategy_records.query_pattern IS '查询模式';
COMMENT ON COLUMN strategy_records.tool_combo IS '工具组合，JSONB格式';
COMMENT ON COLUMN strategy_records.user_feedback IS '用户反馈，JSONB格式';
COMMENT ON COLUMN strategy_records.success_score IS '成功率评分，0.00~1.00';
COMMENT ON COLUMN strategy_records.cost_ms IS '耗时（毫秒）';
COMMENT ON COLUMN strategy_records.is_deleted IS '软删除标记';
COMMENT ON COLUMN strategy_records.created_at IS '创建时间';

CREATE TABLE user_profiles (
    profile_id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             TEXT         NOT NULL,
    profile_version     INTEGER      DEFAULT 1,
    preference          JSONB        NOT NULL,
    interaction_habits  JSONB,
    created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at          TIMESTAMPTZ(3),
    CONSTRAINT uk_user UNIQUE (user_id)
)
;
CREATE INDEX idx_up_updated_at ON user_profiles (updated_at)
;
CREATE INDEX idx_up_pref_gin   ON user_profiles USING GIN (preference)
;
CREATE INDEX idx_up_ih_gin     ON user_profiles USING GIN (interaction_habits)
;
CREATE TRIGGER trg_user_profiles_updated_at
    BEFORE UPDATE ON user_profiles
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON TABLE user_profiles IS '用户画像主表';
COMMENT ON COLUMN user_profiles.profile_id IS '主键，自增ID';
COMMENT ON COLUMN user_profiles.user_id IS '用户标识，唯一';
COMMENT ON COLUMN user_profiles.profile_version IS '画像版本号';
COMMENT ON COLUMN user_profiles.preference IS '用户偏好，JSONB格式';
COMMENT ON COLUMN user_profiles.interaction_habits IS '交互习惯，JSONB格式';
COMMENT ON COLUMN user_profiles.created_at IS '创建时间';
COMMENT ON COLUMN user_profiles.updated_at IS '最后更新时间（触发器自动维护）';
COMMENT ON COLUMN user_profiles.deleted_at IS '软删除时间，非NULL表示已删除';

-- 7. MCP 工具管理
CREATE TABLE mcp_tool (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             TEXT         NOT NULL,
    tool_id             TEXT         NOT NULL,
    tool_name           TEXT         NOT NULL,
    tool_type           TEXT         NOT NULL DEFAULT 'MCP',
    description         TEXT,
    category            TEXT         NOT NULL DEFAULT 'other',
    tags                JSONB,
    mcp_server_url      TEXT,
    transport           TEXT         NOT NULL DEFAULT 'http-sse',
    health_check_url    TEXT,
    input_schema        JSONB        NOT NULL,
    output_schema       JSONB,
    permissions         JSONB,
    risk_level          TEXT         NOT NULL DEFAULT 'low',
    version             TEXT         NOT NULL DEFAULT '1.0.0',
    timeout_seconds     INTEGER      DEFAULT 30,
    retry_count         INTEGER      DEFAULT 1,
    auth_config         JSONB,
    status              TEXT         NOT NULL DEFAULT 'DRAFT',
    health_status       TEXT         NOT NULL DEFAULT 'UNKNOWN',
    last_health_check_at TIMESTAMPTZ(3),
    owner_team          TEXT         DEFAULT 'personal',
    metadata            JSONB,
    created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by          TEXT         NOT NULL,
    updated_by          TEXT         NOT NULL,
    CONSTRAINT uk_user_tool_id   UNIQUE (user_id, tool_id),
    CONSTRAINT uk_user_tool_name UNIQUE (user_id, tool_name)
)
;
CREATE INDEX idx_mt_user_status   ON mcp_tool (user_id, status)
;
CREATE INDEX idx_mt_user_category ON mcp_tool (user_id, category)
;
CREATE INDEX idx_mt_user_tool_type ON mcp_tool (user_id, tool_type)
;
CREATE INDEX idx_mt_health_status ON mcp_tool (health_status)
;
CREATE INDEX idx_mt_tags_gin      ON mcp_tool USING GIN (tags)
;
CREATE INDEX idx_mt_is_gin        ON mcp_tool USING GIN (input_schema)
;
CREATE INDEX idx_mt_os_gin        ON mcp_tool USING GIN (output_schema)
;
CREATE INDEX idx_mt_perms_gin     ON mcp_tool USING GIN (permissions)
;
CREATE INDEX idx_mt_auth_gin      ON mcp_tool USING GIN (auth_config)
;
CREATE INDEX idx_mt_meta_gin      ON mcp_tool USING GIN (metadata)
;
CREATE TRIGGER trg_mcp_tool_updated_at
    BEFORE UPDATE ON mcp_tool
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON TABLE mcp_tool IS 'MCP工具注册表，管理已接入的MCP工具';
COMMENT ON COLUMN mcp_tool.id IS '主键，自增ID';
COMMENT ON COLUMN mcp_tool.user_id IS '所属用户标识';
COMMENT ON COLUMN mcp_tool.tool_id IS '工具编码，用户内唯一';
COMMENT ON COLUMN mcp_tool.tool_name IS '工具显示名称';
COMMENT ON COLUMN mcp_tool.tool_type IS '工具类型：MCP | BUILTIN';
COMMENT ON COLUMN mcp_tool.description IS '工具描述';
COMMENT ON COLUMN mcp_tool.category IS '工具分类：search | code | file | communication | other';
COMMENT ON COLUMN mcp_tool.tags IS '标签数组，JSONB格式';
COMMENT ON COLUMN mcp_tool.mcp_server_url IS 'MCP服务端地址';
COMMENT ON COLUMN mcp_tool.transport IS '传输协议：http-sse | stdio | websocket';
COMMENT ON COLUMN mcp_tool.health_check_url IS '健康检查URL';
COMMENT ON COLUMN mcp_tool.input_schema IS '输入参数Schema，JSONB格式';
COMMENT ON COLUMN mcp_tool.output_schema IS '输出参数Schema，JSONB格式';
COMMENT ON COLUMN mcp_tool.permissions IS '权限声明，JSONB格式';
COMMENT ON COLUMN mcp_tool.risk_level IS '风险等级：low | medium | high | critical';
COMMENT ON COLUMN mcp_tool.version IS '工具版本号';
COMMENT ON COLUMN mcp_tool.timeout_seconds IS '超时时间（秒）';
COMMENT ON COLUMN mcp_tool.retry_count IS '重试次数';
COMMENT ON COLUMN mcp_tool.auth_config IS '认证配置，JSONB格式';
COMMENT ON COLUMN mcp_tool.status IS '工具状态：DRAFT | ACTIVE | INACTIVE | DEPRECATED';
COMMENT ON COLUMN mcp_tool.health_status IS '健康状态：HEALTHY | UNHEALTHY | UNKNOWN';
COMMENT ON COLUMN mcp_tool.last_health_check_at IS '最近一次健康检查时间';
COMMENT ON COLUMN mcp_tool.owner_team IS '归属团队，默认personal';
COMMENT ON COLUMN mcp_tool.metadata IS '扩展元数据，JSONB格式';
COMMENT ON COLUMN mcp_tool.created_at IS '创建时间';
COMMENT ON COLUMN mcp_tool.updated_at IS '最后更新时间（触发器自动维护）';
COMMENT ON COLUMN mcp_tool.created_by IS '创建人';
COMMENT ON COLUMN mcp_tool.updated_by IS '最后更新人';

CREATE TABLE mcp_tool_version (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         TEXT         NOT NULL,
    tool_id         TEXT         NOT NULL,
    version         TEXT         NOT NULL,
    input_schema    JSONB        NOT NULL,
    output_schema   JSONB,
    description     TEXT,
    changelog       TEXT,
    status          TEXT         NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by      TEXT         NOT NULL,
    CONSTRAINT uk_tool_version UNIQUE (user_id, tool_id, version)
)
;
CREATE INDEX idx_mtv_tool_id ON mcp_tool_version (user_id, tool_id)
;
CREATE INDEX idx_mtv_is_gin  ON mcp_tool_version USING GIN (input_schema)
;
CREATE INDEX idx_mtv_os_gin  ON mcp_tool_version USING GIN (output_schema)
;
COMMENT ON TABLE mcp_tool_version IS 'MCP工具版本表，记录工具的版本变更历史';
COMMENT ON COLUMN mcp_tool_version.id IS '主键，自增ID';
COMMENT ON COLUMN mcp_tool_version.user_id IS '所属用户标识';
COMMENT ON COLUMN mcp_tool_version.tool_id IS '工具编码';
COMMENT ON COLUMN mcp_tool_version.version IS '版本号';
COMMENT ON COLUMN mcp_tool_version.input_schema IS '该版本的输入参数Schema';
COMMENT ON COLUMN mcp_tool_version.output_schema IS '该版本的输出参数Schema';
COMMENT ON COLUMN mcp_tool_version.description IS '版本描述';
COMMENT ON COLUMN mcp_tool_version.changelog IS '变更日志';
COMMENT ON COLUMN mcp_tool_version.status IS '版本状态：active | deprecated | retired';
COMMENT ON COLUMN mcp_tool_version.created_at IS '创建时间';
COMMENT ON COLUMN mcp_tool_version.created_by IS '创建人';

CREATE TABLE mcp_tool_audit_log (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id        TEXT         NOT NULL,
    span_id         TEXT         NOT NULL,
    user_id         TEXT         NOT NULL,
    session_id      TEXT,
    tool_id         TEXT         NOT NULL,
    tool_name       TEXT         NOT NULL,
    tool_version    TEXT,
    input_params    JSONB,
    output_preview  TEXT,
    status          TEXT         NOT NULL,
    error_code      TEXT,
    error_msg       TEXT,
    latency_ms      INTEGER,
    request_at      TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT uk_trace_span UNIQUE (trace_id, span_id)
)
;
CREATE INDEX idx_mtal_user_tool   ON mcp_tool_audit_log (user_id, tool_id)
;
CREATE INDEX idx_mtal_status      ON mcp_tool_audit_log (status)
;
CREATE INDEX idx_mtal_request_at  ON mcp_tool_audit_log (request_at)
;
CREATE INDEX idx_mtal_ip_gin      ON mcp_tool_audit_log USING GIN (input_params)
;
CREATE INDEX idx_mtal_brin        ON mcp_tool_audit_log USING BRIN (request_at)
;
COMMENT ON TABLE mcp_tool_audit_log IS 'MCP工具调用审计日志，记录每次工具调用的完整链路';
COMMENT ON COLUMN mcp_tool_audit_log.id IS '主键，自增ID';
COMMENT ON COLUMN mcp_tool_audit_log.trace_id IS '链路追踪ID';
COMMENT ON COLUMN mcp_tool_audit_log.span_id IS '跨度ID';
COMMENT ON COLUMN mcp_tool_audit_log.user_id IS '调用用户标识';
COMMENT ON COLUMN mcp_tool_audit_log.session_id IS '调用会话ID';
COMMENT ON COLUMN mcp_tool_audit_log.tool_id IS '工具编码';
COMMENT ON COLUMN mcp_tool_audit_log.tool_name IS '工具名称';
COMMENT ON COLUMN mcp_tool_audit_log.tool_version IS '工具版本号';
COMMENT ON COLUMN mcp_tool_audit_log.input_params IS '输入参数，JSONB格式';
COMMENT ON COLUMN mcp_tool_audit_log.output_preview IS '输出预览（截断）';
COMMENT ON COLUMN mcp_tool_audit_log.status IS '调用状态：success | error | timeout';
COMMENT ON COLUMN mcp_tool_audit_log.error_code IS '错误码';
COMMENT ON COLUMN mcp_tool_audit_log.error_msg IS '错误信息';
COMMENT ON COLUMN mcp_tool_audit_log.latency_ms IS '耗时（毫秒）';
COMMENT ON COLUMN mcp_tool_audit_log.request_at IS '请求发起时间';

CREATE TABLE mcp_metadata_audit_log (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         TEXT         NOT NULL,
    operator        TEXT         NOT NULL,
    tool_id         TEXT         NOT NULL,
    tool_name       TEXT         NOT NULL,
    operation_type  TEXT         NOT NULL,
    change_summary  TEXT,
    before_snapshot JSONB,
    after_snapshot  JSONB,
    operation_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)
;
CREATE INDEX idx_mmal_user_tool   ON mcp_metadata_audit_log (user_id, tool_id)
;
CREATE INDEX idx_mmal_op_type     ON mcp_metadata_audit_log (operation_type)
;
CREATE INDEX idx_mmal_op_at       ON mcp_metadata_audit_log (operation_at)
;
CREATE INDEX idx_mmal_bs_gin      ON mcp_metadata_audit_log USING GIN (before_snapshot)
;
CREATE INDEX idx_mmal_as_gin      ON mcp_metadata_audit_log USING GIN (after_snapshot)
;
CREATE INDEX idx_mmal_op_at_brin  ON mcp_metadata_audit_log USING BRIN (operation_at)
;
COMMENT ON TABLE mcp_metadata_audit_log IS 'MCP工具元数据变更审计日志，记录工具注册信息的增删改';
COMMENT ON COLUMN mcp_metadata_audit_log.id IS '主键，自增ID';
COMMENT ON COLUMN mcp_metadata_audit_log.user_id IS '操作用户标识';
COMMENT ON COLUMN mcp_metadata_audit_log.operator IS '操作人';
COMMENT ON COLUMN mcp_metadata_audit_log.tool_id IS '工具编码';
COMMENT ON COLUMN mcp_metadata_audit_log.tool_name IS '工具名称';
COMMENT ON COLUMN mcp_metadata_audit_log.operation_type IS '操作类型：CREATE | UPDATE | DELETE | STATUS_CHANGE';
COMMENT ON COLUMN mcp_metadata_audit_log.change_summary IS '变更摘要';
COMMENT ON COLUMN mcp_metadata_audit_log.before_snapshot IS '变更前快照，JSONB格式';
COMMENT ON COLUMN mcp_metadata_audit_log.after_snapshot IS '变更后快照，JSONB格式';
COMMENT ON COLUMN mcp_metadata_audit_log.operation_at IS '操作时间';

-- 8. 通用审计
CREATE TABLE shardflow_audit_log (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         TEXT         NOT NULL,
    tool_name       TEXT,
    params_summary  TEXT,
    success         BOOLEAN      NOT NULL DEFAULT FALSE,
    error           TEXT,
    latency_ms      BIGINT       DEFAULT 0,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)
;
CREATE INDEX idx_audit_user         ON shardflow_audit_log (user_id)
;
CREATE INDEX idx_audit_created      ON shardflow_audit_log (created_at DESC)
;
CREATE INDEX idx_audit_created_brin ON shardflow_audit_log USING BRIN (created_at)
;
COMMENT ON TABLE shardflow_audit_log IS '通用审计日志表，记录系统关键操作';
COMMENT ON COLUMN shardflow_audit_log.id IS '主键，自增ID';
COMMENT ON COLUMN shardflow_audit_log.user_id IS '操作用户标识';
COMMENT ON COLUMN shardflow_audit_log.tool_name IS '工具名称';
COMMENT ON COLUMN shardflow_audit_log.params_summary IS '参数摘要';
COMMENT ON COLUMN shardflow_audit_log.success IS '操作是否成功';
COMMENT ON COLUMN shardflow_audit_log.error IS '错误信息';
COMMENT ON COLUMN shardflow_audit_log.latency_ms IS '耗时（毫秒）';
COMMENT ON COLUMN shardflow_audit_log.created_at IS '操作时间';

-- ============================================================
-- S4: 审计日志字段增强 (C-10.3, C-8.3)
-- ============================================================
ALTER TABLE shardflow_audit_log
    ADD COLUMN IF NOT EXISTS trace_id       TEXT,
    ADD COLUMN IF NOT EXISTS session_id     TEXT,
    ADD COLUMN IF NOT EXISTS operation_type TEXT,
    ADD COLUMN IF NOT EXISTS resource_type  TEXT,
    ADD COLUMN IF NOT EXISTS resource_id    TEXT,
    ADD COLUMN IF NOT EXISTS ip_address     TEXT
;
CREATE INDEX IF NOT EXISTS idx_audit_trace      ON shardflow_audit_log (trace_id)
;
CREATE INDEX IF NOT EXISTS idx_audit_session    ON shardflow_audit_log (session_id)
;
CREATE INDEX IF NOT EXISTS idx_audit_op_type    ON shardflow_audit_log (operation_type)
;
COMMENT ON COLUMN shardflow_audit_log.trace_id IS '链路追踪ID (C-10.2)';
COMMENT ON COLUMN shardflow_audit_log.session_id IS '会话ID';
COMMENT ON COLUMN shardflow_audit_log.operation_type IS '操作类型：CREATE | UPDATE | DELETE | EXPORT | LOGIN | LOGOUT';
COMMENT ON COLUMN shardflow_audit_log.resource_type IS '资源类型：memory | profile | strategy | shard | kb | mcp_tool | user';
COMMENT ON COLUMN shardflow_audit_log.resource_id IS '资源ID';
COMMENT ON COLUMN shardflow_audit_log.ip_address IS '操作IP地址';

-- ============================================================
-- S4: strategy_records 补充 updated_at 字段 (C-7.3 索引要求)
-- ============================================================
ALTER TABLE strategy_records
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
;
CREATE TRIGGER trg_strategy_records_updated_at
    BEFORE UPDATE ON strategy_records
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON COLUMN strategy_records.updated_at IS '最后更新时间（触发器自动维护）';

-- ============================================================
-- S4.5: kb_shard 通用状态包表 (C-2.3-01b, C-3.2-01)
-- ============================================================
CREATE TABLE IF NOT EXISTS kb_shard (
    shard_id        TEXT         PRIMARY KEY,
    shard_type      TEXT         NOT NULL DEFAULT 'session',
    owner_id        TEXT         NOT NULL,
    task_id         TEXT,
    session_id      TEXT,
    context         JSONB,
    memory_refs     JSONB,
    strategy_hints  JSONB,
    retrieved_refs  JSONB,
    status          TEXT         NOT NULL DEFAULT 'active',
    version         INTEGER      NOT NULL DEFAULT 0,
    is_deleted      BOOLEAN      DEFAULT FALSE,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)
;
CREATE INDEX IF NOT EXISTS idx_kbs_owner_type   ON kb_shard (owner_id, shard_type)
;
CREATE INDEX IF NOT EXISTS idx_kbs_status       ON kb_shard (status)
;
CREATE INDEX IF NOT EXISTS idx_kbs_updated_at   ON kb_shard (owner_id, shard_type, updated_at)
;
CREATE INDEX IF NOT EXISTS idx_kbs_context_gin  ON kb_shard USING GIN (context)
;
CREATE TRIGGER trg_kb_shard_updated_at
    BEFORE UPDATE ON kb_shard
    FOR EACH ROW EXECUTE FUNCTION update_timestamp()
;
COMMENT ON TABLE kb_shard IS '通用状态包表 (C-2.3-01b)：Java端驱动状态机，Python更新Redis运行时副本，Java归档PG L2';
COMMENT ON COLUMN kb_shard.shard_id IS '状态包唯一标识';
COMMENT ON COLUMN kb_shard.shard_type IS '状态包类型：session | task | knowledge';
COMMENT ON COLUMN kb_shard.owner_id IS '所有者用户ID（RLS过滤字段）';
COMMENT ON COLUMN kb_shard.task_id IS '关联任务ID';
COMMENT ON COLUMN kb_shard.session_id IS '关联会话ID';
COMMENT ON COLUMN kb_shard.context IS '推理上下文，JSONB格式';
COMMENT ON COLUMN kb_shard.memory_refs IS '记忆引用列表，JSONB格式';
COMMENT ON COLUMN kb_shard.strategy_hints IS '策略提示，JSONB格式';
COMMENT ON COLUMN kb_shard.retrieved_refs IS '检索引用列表，JSONB格式';
COMMENT ON COLUMN kb_shard.status IS '状态：active | archived | deleted';
COMMENT ON COLUMN kb_shard.version IS '版本号（乐观锁，C-6.5）';
COMMENT ON COLUMN kb_shard.is_deleted IS '软删除标记';
COMMENT ON COLUMN kb_shard.created_at IS '创建时间';
COMMENT ON COLUMN kb_shard.updated_at IS '最后更新时间（触发器自动维护）';

-- ============================================================
-- S4.3: user_profile_history 画像变更历史表 (C-9.12)
-- ============================================================
CREATE TABLE IF NOT EXISTS user_profile_history (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         TEXT         NOT NULL,
    profile_version INTEGER      NOT NULL,
    change_type     TEXT         NOT NULL DEFAULT 'UPDATE',
    patch           JSONB,
    before_snapshot JSONB,
    after_snapshot  JSONB,
    source          TEXT,
    trace_id        TEXT,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)
;
CREATE INDEX IF NOT EXISTS idx_uph_user_version ON user_profile_history (user_id, profile_version)
;
CREATE INDEX IF NOT EXISTS idx_uph_created_at   ON user_profile_history (created_at)
;
COMMENT ON TABLE user_profile_history IS '用户画像变更历史表 (C-9.12)：记录每次画像更新的增量补丁与快照';

-- ============================================================
-- 9. Skills 管理 (P1 / DR-1)
-- 设计决策：user_id 等用户标识采用 TEXT（与现有约定一致）；
--          description 全文索引用 to_tsvector+GIN；RLS 仅 skill_registry
-- ============================================================
CREATE TABLE IF NOT EXISTS skill_registry (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_code        VARCHAR(64)  NOT NULL,
    skill_name        VARCHAR(128) NOT NULL,
    description       TEXT,
    skill_type        VARCHAR(16)  NOT NULL DEFAULT 'prompt',
    trust_tier        VARCHAR(16)  NOT NULL DEFAULT 'personal',
    owner_id          TEXT         NOT NULL,
    user_id           TEXT         NOT NULL,
    current_version   VARCHAR(32)  NOT NULL DEFAULT '',
    status            VARCHAR(16)  NOT NULL DEFAULT 'draft',
    trigger_keywords  JSONB,
    input_schema      JSONB,
    output_schema     JSONB,
    cost_estimate     JSONB,
    config            JSONB,
    tags              JSONB,
    source            VARCHAR(16)  NOT NULL DEFAULT 'CUSTOM',
    created_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by        TEXT         NOT NULL,
    updated_by        TEXT         NOT NULL,
    CONSTRAINT uk_skill_code   UNIQUE (skill_code),
    CONSTRAINT ck_skill_type   CHECK (skill_type IN ('prompt','tool','hybrid','workflow')),
    CONSTRAINT ck_trust_tier   CHECK (trust_tier IN ('official','team','personal')),
    CONSTRAINT ck_skill_status CHECK (status IN ('draft','reviewing','published','deprecated','archived')),
    CONSTRAINT ck_skill_source CHECK (source IN ('CUSTOM','IMPORTED','BUILTIN'))
);
CREATE INDEX IF NOT EXISTS idx_skill_registry_user_status ON skill_registry (user_id, status);
CREATE INDEX IF NOT EXISTS idx_skill_registry_owner       ON skill_registry (owner_id);
CREATE INDEX IF NOT EXISTS idx_skill_registry_trust_tier  ON skill_registry (trust_tier);
CREATE INDEX IF NOT EXISTS idx_skill_registry_ft_desc     ON skill_registry USING GIN (to_tsvector('simple', COALESCE(description, '')));
CREATE TRIGGER trg_skill_registry_updated_at
    BEFORE UPDATE ON skill_registry
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();
COMMENT ON TABLE skill_registry IS 'Skill 注册表，存储 Skill 元数据与生命周期状态';
COMMENT ON COLUMN skill_registry.skill_code IS 'Skill 唯一编码，格式 SKILL-{8位UUID短码}';
COMMENT ON COLUMN skill_registry.skill_name IS 'Skill 显示名称，最长128字符';
COMMENT ON COLUMN skill_registry.skill_type IS '执行模式：prompt | tool | hybrid | workflow';
COMMENT ON COLUMN skill_registry.trust_tier IS '信任等级：official | team | personal';
COMMENT ON COLUMN skill_registry.user_id IS '所属用户标识（RLS过滤字段）';
COMMENT ON COLUMN skill_registry.current_version IS '当前生效版本号';
COMMENT ON COLUMN skill_registry.status IS '状态：draft | reviewing | published | deprecated | archived';
COMMENT ON COLUMN skill_registry.source IS '来源：CUSTOM | IMPORTED | BUILTIN';

CREATE TABLE IF NOT EXISTS skill_version (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id        BIGINT       NOT NULL,
    version_tag     VARCHAR(32)  NOT NULL,
    content_hash    VARCHAR(64)  NOT NULL,
    artifact_path   VARCHAR(512) NOT NULL,
    change_log      TEXT,
    promoted_by     TEXT,
    promoted_at     TIMESTAMPTZ(3),
    status          VARCHAR(16)  NOT NULL DEFAULT 'draft',
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_skill_version UNIQUE (skill_id, version_tag),
    CONSTRAINT ck_version_status CHECK (status IN ('draft','staging','production','rolled_back')),
    CONSTRAINT fk_skill_version_registry FOREIGN KEY (skill_id)
        REFERENCES skill_registry (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_skill_version_skill_id ON skill_version (skill_id);
CREATE INDEX IF NOT EXISTS idx_skill_version_status   ON skill_version (status);
COMMENT ON TABLE skill_version IS 'Skill 版本历史表，记录不可变版本与发布信息';

CREATE TABLE IF NOT EXISTS skill_artifact (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id        BIGINT       NOT NULL,
    version_id      BIGINT       NOT NULL,
    artifact_type   VARCHAR(32)  NOT NULL,
    file_name       VARCHAR(128) NOT NULL,
    file_size       INTEGER      NOT NULL,
    content_hash    VARCHAR(64)  NOT NULL,
    minio_url       VARCHAR(512) NOT NULL,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_skill_artifact UNIQUE (skill_id, version_id, artifact_type, file_name),
    CONSTRAINT ck_artifact_type CHECK (artifact_type IN ('metadata','prompt','tool_handler','workflow_def','manifest')),
    CONSTRAINT fk_skill_artifact_registry FOREIGN KEY (skill_id)
        REFERENCES skill_registry (id) ON DELETE CASCADE,
    CONSTRAINT fk_skill_artifact_version FOREIGN KEY (version_id)
        REFERENCES skill_version (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_skill_artifact_version ON skill_artifact (version_id);
COMMENT ON TABLE skill_artifact IS 'Skill 内容元数据表，记录每个版本的 Artifact 文件信息';

CREATE TABLE IF NOT EXISTS agent_skill_binding (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id        TEXT         NOT NULL,
    skill_id        BIGINT       NOT NULL,
    bound_version   VARCHAR(32)  NOT NULL,
    binding_type    VARCHAR(16)  NOT NULL DEFAULT 'optional',
    priority        INTEGER      NOT NULL DEFAULT 0,
    config_override JSONB,
    enabled         SMALLINT     NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by      TEXT         NOT NULL,
    CONSTRAINT uk_agent_skill UNIQUE (agent_id, skill_id),
    CONSTRAINT ck_binding_type CHECK (binding_type IN ('required','optional')),
    CONSTRAINT fk_agent_skill_registry FOREIGN KEY (skill_id)
        REFERENCES skill_registry (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_agent_skill_agent ON agent_skill_binding (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_skill_skill ON agent_skill_binding (skill_id);
CREATE TRIGGER trg_agent_skill_binding_updated_at
    BEFORE UPDATE ON agent_skill_binding
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();
COMMENT ON TABLE agent_skill_binding IS 'Agent-Skill 绑定关系表，管理 Agent 挂载的 Skill';

CREATE TABLE IF NOT EXISTS skill_permission (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id        BIGINT       NOT NULL,
    subject_type    VARCHAR(16)  NOT NULL,
    subject_id      TEXT         NOT NULL,
    permission_mask INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_skill_subject UNIQUE (skill_id, subject_type, subject_id),
    CONSTRAINT ck_subject_type CHECK (subject_type IN ('user','role','team','tenant')),
    CONSTRAINT fk_skill_permission_registry FOREIGN KEY (skill_id)
        REFERENCES skill_registry (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_skill_permission_subject ON skill_permission (subject_type, subject_id);
COMMENT ON TABLE skill_permission IS 'Skill 权限配置表，RBAC+ABAC 位掩码权限模型';

CREATE TABLE IF NOT EXISTS skill_audit_log (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id        BIGINT,
    agent_id        TEXT,
    session_id      VARCHAR(64),
    operation       VARCHAR(64)  NOT NULL,
    operator_id     TEXT         NOT NULL,
    operator_type   VARCHAR(16)  NOT NULL DEFAULT 'user',
    request_id      VARCHAR(64),
    details         JSONB,
    ip_address      VARCHAR(64),
    user_agent      VARCHAR(512),
    latency_ms      INTEGER      NOT NULL DEFAULT 0,
    tokens_used     INTEGER      NOT NULL DEFAULT 0,
    success         BOOLEAN      NOT NULL DEFAULT TRUE,
    error           TEXT,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT ck_operator_type CHECK (operator_type IN ('user','system','api'))
);
CREATE INDEX IF NOT EXISTS idx_skill_audit_skill     ON skill_audit_log (skill_id);
CREATE INDEX IF NOT EXISTS idx_skill_audit_agent     ON skill_audit_log (agent_id);
CREATE INDEX IF NOT EXISTS idx_skill_audit_session   ON skill_audit_log (session_id);
CREATE INDEX IF NOT EXISTS idx_skill_audit_operation ON skill_audit_log (operation);
CREATE INDEX IF NOT EXISTS idx_skill_audit_created   ON skill_audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_skill_audit_request   ON skill_audit_log (request_id);
CREATE INDEX IF NOT EXISTS idx_skill_audit_brin      ON skill_audit_log USING BRIN (created_at);
COMMENT ON TABLE skill_audit_log IS 'Skill 审计日志表，记录所有 Skill 操作与执行调用（含性能指标 latency_ms/tokens_used）';

-- ============================================================
-- S4.7: RLS 行级安全策略 (C-4.1-01)
-- 规则：所有业务表按 user_id 过滤，service 角色可访问全部数据
-- ============================================================

-- 启用 RLS（所有含 user_id 的业务表）
ALTER TABLE shardflow_task             ENABLE ROW LEVEL SECURITY;
ALTER TABLE shardflow_task_session     ENABLE ROW LEVEL SECURITY;
ALTER TABLE shardflow_agent_config     ENABLE ROW LEVEL SECURITY;
ALTER TABLE shardflow_custom_model     ENABLE ROW LEVEL SECURITY;
ALTER TABLE shardflow_model_audit_log  ENABLE ROW LEVEL SECURITY;
ALTER TABLE shardflow_kb_collection    ENABLE ROW LEVEL SECURITY;
ALTER TABLE shardflow_kb_document      ENABLE ROW LEVEL SECURITY;
ALTER TABLE shardflow_kb_strategy      ENABLE ROW LEVEL SECURITY;
ALTER TABLE memory_chunks              ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_state_summaries    ENABLE ROW LEVEL SECURITY;
ALTER TABLE strategy_records           ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles              ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_tool                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_tool_version           ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_tool_audit_log         ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_metadata_audit_log     ENABLE ROW LEVEL SECURITY;
ALTER TABLE shardflow_audit_log        ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb_shard                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profile_history       ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_registry             ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略：user_id 匹配 或 service 角色放行
-- USING 作用于 SELECT/UPDATE/DELETE 的行过滤
-- WITH CHECK 作用于 INSERT/UPDATE 的新行校验
CREATE POLICY rls_task_isolation ON shardflow_task
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_task_session_isolation ON shardflow_task_session
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_agent_config_isolation ON shardflow_agent_config
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_custom_model_isolation ON shardflow_custom_model
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_model_audit_isolation ON shardflow_model_audit_log
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_kb_collection_isolation ON shardflow_kb_collection
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_kb_document_isolation ON shardflow_kb_document
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_kb_strategy_isolation ON shardflow_kb_strategy
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_memory_chunks_isolation ON memory_chunks
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_session_state_summaries_isolation ON session_state_summaries
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_strategy_records_isolation ON strategy_records
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_user_profiles_isolation ON user_profiles
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_mcp_tool_isolation ON mcp_tool
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_mcp_tool_version_isolation ON mcp_tool_version
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_mcp_tool_audit_isolation ON mcp_tool_audit_log
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_mcp_metadata_audit_isolation ON mcp_metadata_audit_log
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_audit_log_isolation ON shardflow_audit_log
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_kb_shard_isolation ON kb_shard
    USING (owner_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (owner_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_user_profile_history_isolation ON user_profile_history
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

CREATE POLICY rls_skill_registry_isolation ON skill_registry
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');

-- 种子数据
INSERT INTO shardflow_model_builtin (model_code, name, provider, model, base_url, api_key_env, capabilities, context_window, sort_order)
VALUES
    ('gpt-4o',           'GPT-4o',           'openai',    'gpt-4o',           'https://api.openai.com/v1',    'OPENAI_API_KEY',    '["chat","vision","function_calling"]', 128000, 1),
    ('gpt-4o-mini',      'GPT-4o Mini',      'openai',    'gpt-4o-mini',      'https://api.openai.com/v1',    'OPENAI_API_KEY',    '["chat","vision"]',                    128000, 2),
    ('deepseek-chat',    'DeepSeek Chat',    'deepseek',  'deepseek-chat',     'https://api.deepseek.com/v1',  'DEEPSEEK_API_KEY',   '["chat","reasoning"]',                  64000, 3),
    ('claude-sonnet-4-6','Claude Sonnet 4.6','anthropic', 'claude-sonnet-4-6', 'https://api.anthropic.com/v1', 'ANTHROPIC_API_KEY',  '["chat","vision"]',                    200000, 4),
    ('claude-opus-4-8',  'Claude Opus 4.8',  'anthropic', 'claude-opus-4-8',  'https://api.anthropic.com/v1', 'ANTHROPIC_API_KEY',  '["chat","vision","reasoning"]',         200000, 5)
ON CONFLICT (model_code) DO NOTHING
;
