-- ============================================================
-- ShardFlow Skills 管理 — 数据模型与基础设施 (P1)
-- 版本: V1
-- 关联需求: DR-1 (规格文档 7.1.1 ~ 7.1.6)
-- 说明: 建立 6 张 PostgreSQL 表，支撑 Skill 注册/版本/工件/绑定/权限/审计
-- 设计决策:
--   1. user_id / owner_id / created_by / updated_by / operator_id 采用 TEXT 类型
--      (与现有 shardflow_agent_config / mcp_tool 约定一致，确保 RLS 与 UserContext 集成)
--   2. description 全文索引采用 PostgreSQL to_tsvector + GIN (规格 FULLTEXT KEY 为 MySQL 语法)
--   3. RLS 仅启用在 skill_registry (含 user_id)；子表通过 skill_id 外键 + 应用层 UserContext 隔离
-- ============================================================

-- ============================================================
-- 1. skill_registry — Skill 注册表 (DR-1 / 7.1.1)
-- ============================================================
CREATE TABLE skill_registry (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_code        VARCHAR(64)  NOT NULL,
    skill_name        VARCHAR(128) NOT NULL,
    description       TEXT,
    skill_type        VARCHAR(16)  NOT NULL DEFAULT 'prompt',
    trust_tier        VARCHAR(16)  NOT NULL DEFAULT 'personal',
    owner_id          TEXT         NOT NULL,
    user_id           TEXT         NOT NULL,
    current_version   VARCHAR(32)  NOT NULL,
    status            VARCHAR(16)  NOT NULL DEFAULT 'draft',
    trigger_keywords  JSONB,
    input_schema      JSONB,
    output_schema     JSONB,
    cost_estimate     JSONB,
    tags              JSONB,
    category          VARCHAR(64)  DEFAULT '',
    source            VARCHAR(16)  NOT NULL DEFAULT 'CUSTOM',
    created_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by        TEXT         NOT NULL,
    updated_by        TEXT         NOT NULL,
    CONSTRAINT uk_skill_code   UNIQUE (skill_code),
    CONSTRAINT ck_skill_type   CHECK (skill_type IN ('prompt','tool','hybrid','workflow')),
    CONSTRAINT ck_trust_tier   CHECK (trust_tier IN ('official','team','personal')),
    CONSTRAINT ck_skill_status CHECK (status IN ('draft','reviewing','published','deprecated','archived')),
    CONSTRAINT ck_skill_source CHECK (source IN ('CUSTOM','IMPORTED','BUILTIN'))
);
CREATE INDEX idx_skill_registry_user_status ON skill_registry (user_id, status);
CREATE INDEX idx_skill_registry_owner       ON skill_registry (owner_id);
CREATE INDEX idx_skill_registry_trust_tier  ON skill_registry (trust_tier);
CREATE INDEX idx_skill_registry_category    ON skill_registry (category);
CREATE INDEX idx_skill_registry_ft_desc     ON skill_registry USING GIN (to_tsvector('simple', COALESCE(description, '')));
CREATE TRIGGER trg_skill_registry_updated_at
    BEFORE UPDATE ON skill_registry
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();
COMMENT ON TABLE skill_registry IS 'Skill 注册表，存储 Skill 元数据与生命周期状态';
COMMENT ON COLUMN skill_registry.id IS '主键，自增ID';
COMMENT ON COLUMN skill_registry.skill_code IS 'Skill 唯一编码，格式 SKILL-{8位UUID短码}';
COMMENT ON COLUMN skill_registry.skill_name IS 'Skill 显示名称，最长128字符';
COMMENT ON COLUMN skill_registry.description IS 'Skill 描述，用于语义检索与 LLM 决策';
COMMENT ON COLUMN skill_registry.skill_type IS '执行模式：prompt | tool | hybrid | workflow';
COMMENT ON COLUMN skill_registry.trust_tier IS '信任等级：official | team | personal';
COMMENT ON COLUMN skill_registry.owner_id IS '创建者用户ID';
COMMENT ON COLUMN skill_registry.user_id IS '所属用户标识（RLS过滤字段）';
COMMENT ON COLUMN skill_registry.current_version IS '当前生效版本号';
COMMENT ON COLUMN skill_registry.status IS '状态：draft | reviewing | published | deprecated | archived';
COMMENT ON COLUMN skill_registry.trigger_keywords IS '触发关键词列表，JSONB格式';
COMMENT ON COLUMN skill_registry.input_schema IS '输入参数 JSON Schema';
COMMENT ON COLUMN skill_registry.output_schema IS '输出参数 JSON Schema';
COMMENT ON COLUMN skill_registry.cost_estimate IS '预估成本，JSONB格式';
COMMENT ON COLUMN skill_registry.tags IS '标签列表，JSONB格式';
COMMENT ON COLUMN skill_registry.category IS '技能分类';
COMMENT ON COLUMN skill_registry.source IS '来源：CUSTOM | IMPORTED | BUILTIN';
COMMENT ON COLUMN skill_registry.created_at IS '创建时间';
COMMENT ON COLUMN skill_registry.updated_at IS '最后更新时间（触发器自动维护）';
COMMENT ON COLUMN skill_registry.created_by IS '创建者';
COMMENT ON COLUMN skill_registry.updated_by IS '最后更新者';

-- ============================================================
-- 2. skill_version — Skill 版本历史 (DR-1 / 7.1.2)
-- ============================================================
CREATE TABLE skill_version (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id        BIGINT       NOT NULL,
    version_tag     VARCHAR(32)  NOT NULL,
    content_hash    VARCHAR(64)  NOT NULL,
    artifact_path   VARCHAR(512) NOT NULL,
    change_log      TEXT,
    promoted_by     TEXT,
    promoted_at     TIMESTAMPTZ(3),
    status          VARCHAR(16)  NOT NULL DEFAULT 'draft',
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_skill_version UNIQUE (skill_id, version_tag),
    CONSTRAINT ck_version_status CHECK (status IN ('draft','staging','production','rolled_back')),
    CONSTRAINT fk_skill_version_registry FOREIGN KEY (skill_id)
        REFERENCES skill_registry (id) ON DELETE CASCADE
);
CREATE INDEX idx_skill_version_skill_id ON skill_version (skill_id);
CREATE INDEX idx_skill_version_status   ON skill_version (status);
COMMENT ON TABLE skill_version IS 'Skill 版本历史表，记录不可变版本与发布信息';
COMMENT ON COLUMN skill_version.id IS '主键，自增ID';
COMMENT ON COLUMN skill_version.skill_id IS '关联 skill_registry.id';
COMMENT ON COLUMN skill_version.version_tag IS '版本标签，MAJOR.MINOR.PATCH 格式';
COMMENT ON COLUMN skill_version.content_hash IS '内容 SHA-256 哈希';
COMMENT ON COLUMN skill_version.artifact_path IS 'MinIO 存储路径';
COMMENT ON COLUMN skill_version.change_log IS '变更说明（发布时必填）';
COMMENT ON COLUMN skill_version.promoted_by IS '发布者ID';
COMMENT ON COLUMN skill_version.promoted_at IS '发布时间';
COMMENT ON COLUMN skill_version.status IS '版本状态：draft | staging | production | rolled_back';
COMMENT ON COLUMN skill_version.created_at IS '创建时间';

-- ============================================================
-- 3. skill_artifact — Skill 内容元数据 (DR-1 / 7.1.3)
-- ============================================================
CREATE TABLE skill_artifact (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id        BIGINT       NOT NULL,
    version_id      BIGINT       NOT NULL,
    artifact_type   VARCHAR(32)  NOT NULL,
    file_name       VARCHAR(128) NOT NULL,
    file_size       INTEGER      NOT NULL,
    content_hash    VARCHAR(64)  NOT NULL,
    minio_url       VARCHAR(512) NOT NULL,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_skill_artifact UNIQUE (skill_id, version_id, artifact_type, file_name),
    CONSTRAINT ck_artifact_type CHECK (artifact_type IN ('metadata','prompt','tool_handler','workflow_def','manifest')),
    CONSTRAINT fk_skill_artifact_registry FOREIGN KEY (skill_id)
        REFERENCES skill_registry (id) ON DELETE CASCADE,
    CONSTRAINT fk_skill_artifact_version FOREIGN KEY (version_id)
        REFERENCES skill_version (id) ON DELETE CASCADE
);
CREATE INDEX idx_skill_artifact_version ON skill_artifact (version_id);
COMMENT ON TABLE skill_artifact IS 'Skill 内容元数据表，记录每个版本的 Artifact 文件信息';
COMMENT ON COLUMN skill_artifact.id IS '主键，自增ID';
COMMENT ON COLUMN skill_artifact.skill_id IS '关联 skill_registry.id';
COMMENT ON COLUMN skill_artifact.version_id IS '关联 skill_version.id';
COMMENT ON COLUMN skill_artifact.artifact_type IS '工件类型：metadata | prompt | tool_handler | workflow_def | manifest';
COMMENT ON COLUMN skill_artifact.file_name IS '文件名';
COMMENT ON COLUMN skill_artifact.file_size IS '文件大小（字节）';
COMMENT ON COLUMN skill_artifact.content_hash IS '内容哈希（SHA-256）';
COMMENT ON COLUMN skill_artifact.minio_url IS 'MinIO 对象存储路径';
COMMENT ON COLUMN skill_artifact.created_at IS '创建时间';

-- ============================================================
-- 4. agent_skill_binding — Agent-Skill 绑定关系 (DR-1 / 7.1.4)
-- ============================================================
CREATE TABLE agent_skill_binding (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id        TEXT         NOT NULL,
    skill_id        BIGINT       NOT NULL,
    bound_version   VARCHAR(32)  NOT NULL,
    binding_type    VARCHAR(16)  NOT NULL DEFAULT 'optional',
    priority        INTEGER      NOT NULL DEFAULT 0,
    config_override JSONB,
    enabled         SMALLINT     NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by      TEXT         NOT NULL,
    CONSTRAINT uk_agent_skill UNIQUE (agent_id, skill_id),
    CONSTRAINT ck_binding_type CHECK (binding_type IN ('required','optional')),
    CONSTRAINT fk_agent_skill_registry FOREIGN KEY (skill_id)
        REFERENCES skill_registry (id) ON DELETE CASCADE
);
CREATE INDEX idx_agent_skill_agent ON agent_skill_binding (agent_id);
CREATE INDEX idx_agent_skill_skill ON agent_skill_binding (skill_id);
CREATE TRIGGER trg_agent_skill_binding_updated_at
    BEFORE UPDATE ON agent_skill_binding
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();
COMMENT ON TABLE agent_skill_binding IS 'Agent-Skill 绑定关系表，管理 Agent 挂载的 Skill';
COMMENT ON COLUMN agent_skill_binding.id IS '主键，自增ID';
COMMENT ON COLUMN agent_skill_binding.agent_id IS 'Agent 编码（关联 shardflow_agent_config.agent_code）';
COMMENT ON COLUMN agent_skill_binding.skill_id IS '关联 skill_registry.id';
COMMENT ON COLUMN agent_skill_binding.bound_version IS '绑定的 Skill 版本号';
COMMENT ON COLUMN agent_skill_binding.binding_type IS '绑定类型：required | optional';
COMMENT ON COLUMN agent_skill_binding.priority IS '优先级，数值越大优先级越高';
COMMENT ON COLUMN agent_skill_binding.config_override IS 'Agent 级别的配置覆盖，JSONB格式';
COMMENT ON COLUMN agent_skill_binding.enabled IS '是否启用：1=启用 0=禁用';
COMMENT ON COLUMN agent_skill_binding.created_at IS '创建时间';
COMMENT ON COLUMN agent_skill_binding.updated_at IS '最后更新时间（触发器自动维护）';
COMMENT ON COLUMN agent_skill_binding.created_by IS '创建者';

-- ============================================================
-- 5. skill_permission — Skill 权限配置 (DR-1 / 7.1.5)
-- ============================================================
CREATE TABLE skill_permission (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id        BIGINT       NOT NULL,
    subject_type    VARCHAR(16)  NOT NULL,
    subject_id      TEXT         NOT NULL,
    permission_mask INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_skill_subject UNIQUE (skill_id, subject_type, subject_id),
    CONSTRAINT ck_subject_type CHECK (subject_type IN ('user','role','team','tenant')),
    CONSTRAINT fk_skill_permission_registry FOREIGN KEY (skill_id)
        REFERENCES skill_registry (id) ON DELETE CASCADE
);
CREATE INDEX idx_skill_permission_subject ON skill_permission (subject_type, subject_id);
COMMENT ON TABLE skill_permission IS 'Skill 权限配置表，RBAC+ABAC 位掩码权限模型';
COMMENT ON COLUMN skill_permission.id IS '主键，自增ID';
COMMENT ON COLUMN skill_permission.skill_id IS '关联 skill_registry.id';
COMMENT ON COLUMN skill_permission.subject_type IS '权限主体类型：user | role | team | tenant';
COMMENT ON COLUMN skill_permission.subject_id IS '权限主体ID';
COMMENT ON COLUMN skill_permission.permission_mask IS '位掩码：1=读 2=写 4=执行 8=管理 16=审计';
COMMENT ON COLUMN skill_permission.created_at IS '创建时间';

-- ============================================================
-- 6. skill_audit_log — Skill 审计日志 (DR-1 / 7.1.6)
-- ============================================================
CREATE TABLE skill_audit_log (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id        BIGINT,
    agent_id        TEXT,
    operation       VARCHAR(64)  NOT NULL,
    operator_id     TEXT         NOT NULL,
    operator_type   VARCHAR(16)  NOT NULL DEFAULT 'user',
    request_id      VARCHAR(64),
    details         JSONB,
    ip_address      VARCHAR(64),
    user_agent      VARCHAR(512),
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT ck_operator_type CHECK (operator_type IN ('user','system','api'))
);
CREATE INDEX idx_skill_audit_skill     ON skill_audit_log (skill_id);
CREATE INDEX idx_skill_audit_agent     ON skill_audit_log (agent_id);
CREATE INDEX idx_skill_audit_operation ON skill_audit_log (operation);
CREATE INDEX idx_skill_audit_created   ON skill_audit_log (created_at DESC);
CREATE INDEX idx_skill_audit_request   ON skill_audit_log (request_id);
CREATE INDEX idx_skill_audit_brin      ON skill_audit_log USING BRIN (created_at);
COMMENT ON TABLE skill_audit_log IS 'Skill 审计日志表，记录所有 Skill 操作与执行调用';
COMMENT ON COLUMN skill_audit_log.id IS '主键，自增ID';
COMMENT ON COLUMN skill_audit_log.skill_id IS 'Skill ID（可为空，如批量操作）';
COMMENT ON COLUMN skill_audit_log.agent_id IS 'Agent 编码（执行调用时记录）';
COMMENT ON COLUMN skill_audit_log.operation IS '操作类型：CREATE | UPDATE | DELETE | STATUS_CHANGE | PUBLISH | ROLLBACK | PERMISSION_CHANGE | EXECUTE | IMPORT | EXPORT';
COMMENT ON COLUMN skill_audit_log.operator_id IS '操作者ID';
COMMENT ON COLUMN skill_audit_log.operator_type IS '操作者类型：user | system | api';
COMMENT ON COLUMN skill_audit_log.request_id IS '请求ID，用于链路追踪';
COMMENT ON COLUMN skill_audit_log.details IS '操作详情，JSONB格式';
COMMENT ON COLUMN skill_audit_log.ip_address IS 'IP 地址';
COMMENT ON COLUMN skill_audit_log.user_agent IS 'User-Agent';
COMMENT ON COLUMN skill_audit_log.created_at IS '操作时间';

-- ============================================================
-- RLS 行级安全策略 (C-4.1-01)
-- 仅 skill_registry 含 user_id，按 user_id 隔离
-- 子表通过 skill_id 外键关联 + 应用层 UserContext 隔离保护
-- ============================================================
ALTER TABLE skill_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY rls_skill_registry_isolation ON skill_registry
    USING (user_id = current_setting('app.current_user_id', true)
           OR current_setting('app.current_user_id', true) = 'service')
    WITH CHECK (user_id = current_setting('app.current_user_id', true)
                OR current_setting('app.current_user_id', true) = 'service');
