-- ============================================================
-- V5: Create mcp_quick_template table
-- Description: 场景模板存储表，用于 MCP 快速配置的场景模板管理
-- Per design doc section 5.2: 数据模型设计
-- ============================================================

CREATE TABLE mcp_quick_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id     VARCHAR(128) NOT NULL,          -- 模板标识，如 "@mcp/feishu"
    display_name    VARCHAR(128) NOT NULL,           -- 展示名称，如 "飞书"
    category        VARCHAR(64) NOT NULL DEFAULT 'other',   -- 模板分类
    description     TEXT,                            -- 模板描述
    icon_url        VARCHAR(512),                    -- 图标地址

    -- 默认连接配置
    transport       VARCHAR(16) NOT NULL,           -- stdio / sse / cloud
    default_connection JSONB NOT NULL,              -- 默认连接信息

    -- 预置 Schema
    input_schema    JSONB NOT NULL,                 -- 工具 input_schema
    output_schema   JSONB,                          -- 工具 output_schema

    -- 预置参数
    default_env_vars JSONB,                        -- 需要的环境变量名列表 ["FEISHU_APP_ID", "FEISHU_APP_SECRET"]
    env_var_descriptions JSONB,                    -- 环境变量说明 {"FEISHU_APP_ID": "飞书应用 ID"}

    -- 认证配置
    auth_type       VARCHAR(32) DEFAULT 'none',    -- none / bearer / api_key / oauth2 / gcp-iam / aws-iam

    -- 模板元数据
    version         VARCHAR(16) DEFAULT '1.0.0',
    status          VARCHAR(16) DEFAULT 'ACTIVE',
    sort_order      INT DEFAULT 0,                  -- 排序权重
    tags            JSONB,                          -- 搜索标签

    -- 审计字段
    created_at      TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_mqt_template_id ON mcp_quick_template (template_id);
CREATE INDEX idx_mqt_category ON mcp_quick_template (category);
CREATE INDEX idx_mqt_status ON mcp_quick_template (status);